### ISSUE TITLE
Segmentation fault (core dumped) with Irrlicht Visualization

### ISSUE THREAD

**Issue by arjunds** [jmccormac/pySceneNetRGBD#23]
I keep getting this error when uncommenting the Irrlicht visualization code in scenenet_room_generator.cpp. I want to be able to visualize the scene without rendering the images in renderer so this seemed like how I would do it. After a long time debugging, I still have yet to find a solution that will help me work around this error
Any help would be appreciated!

**Comment by jmccormac** [comment]
Unfortunately I have been unable to reproduce this, so it's a bit tricky to track down.  Just to be clear we are doing the same thing, to show the visualiser in ```scenenet_room_generator.cpp``` I uncommented lines 603-615 and 732-754, and commented out lines 726-728.  When I did this it visualised the physics scene without a problem. I previously used irrlicht 1.8.2 without problem but on my current system I am using a slightly updated 1.8.3 version of [irrlicht](downloads.sourceforge.net/irrlicht/irrlicht-1.8.3.zip) - can you try that version to see if it helps? 

Also, have you tried compiling with the -g flag (to the ```CMakeLists.txt``` e.g. ```COMPILE_FLAGS "${CHRONO_CXX_FLAGS} -g"```)  so that you can pinpoint the error with gdb ([here's](http://www.unknownroad.com/rtfm/gdbtut/gdbsegfault.html) an example tutorial showing how to pinpoint segfaults with gdb).

**Comment by arjunds** [comment]
Alright so using irrlicht 1.8.3 seems to have fixed the problem, but now I just see the layout but none of the objects in it. Is this what the visualizer is supposed to do?

Also how would one go about adding their own objects to the program. I looked through the textfiles/ directory and looked through all the files. From what I understand, I just need to edit train_split_filtered_model_info_and_texture.txt and wnid_sample_probabilities.txt. However, since you did this for tens of thousands of objects, do you have a script to automate it already?
Thanks!
