### ISSUE TITLE
Get object locations / bounding boxes

### ISSUE THREAD

**Issue by maxizi** [jmccormac/pySceneNetRGBD#35]
Hi together,

For each video, I am trying to get the bounding boxes of the objects (without background) and store them in some format, which could e.g. be one txt file per video. So far, I am not quite getting there, but trying my best..

Has anyone tried to do something like this? Help would be appreciated.

Thanks!

**Comment by ankurhanda** [comment]
The dataset provides depth as well as segmentation. You also know the camera pose so you can align the depth map to gravity to obtain the height. However, in some cases it won't be possible to get all bbox dimensions because you may not have a good view of the object so getting breadth of the cuboid would be tricky. (width is size on X-axis on 2D image back-projected in 3D, height is size on Y axis on 2D image back-projected in 3D again and you get these sizes from bbox on 2D image segmentation and then back-project them to 3D).

**Comment by maxizi** [comment]
Thanks for your assessment.

**Comment by amitbcp** [comment]
@maxizi did you try converting and getting the 2D bounding box for the object ?
I am looking for something similar, where I want to get the 2D Bounding Box & 3D Box for every frame

**Comment by Cindy0725** [comment]
Same questions here, I also want to use the 3D and 2D bounding boxes but don't know how to extract the precise one
